### ISSUE TITLE
發文失敗，不斷彈出視窗

### ISSUE THREAD

**Issue by MoseHas** [kobeengineer/init#10]
![image](https://user-images.githubusercontent.com/12470315/29031571-4b4ab0e8-7bc1-11e7-8a94-c0c83b3db749.png)

無論有無勾選「我同意並已詳細閱讀使用條款及本站隱私權政策」
都會彈出此視窗

嘗試過重新登入GitHub還是無效

目前已測試過所有發文模式，optional欄位也嘗試過，都無法發出

測試系統：Windows 10 home
測試環境：Chrome  60.0.3112.90

**Comment by brownsugar** [comment]
你沒「詳細」閱讀發文守則，結案。

**Comment by kxgio** [comment]
看吧，果然有效

**Comment by MoseHas** [comment]
靠北為什麼要搞這種到處藏的...

**Comment by Clangxp** [comment]
我也看好久才看到那個框....
