### ISSUE TITLE
github的網址有問題

### ISSUE THREAD

**Issue by maple3142** [kobeengineer/init#14]
如題
這個[連結](https://init.kobeengineer.io/post/?id=1)下方的**GITHUB**按鈕連結到的[網址](https://github.com/kobeengineer/init/tree/master/post-1)會出現404
正確的網址應該是[https://github.com/kobeengineer/init/tree/master/post-1-1000/post-1](https://github.com/kobeengineer/init/tree/master/post-1-1000/post-1)

**Comment by kxgio** [comment]
fixed.
