### ISSUE TITLE
hello world

### ISSUE THREAD

**Issue by b03611010** [kobeengineer/init#15]
手機顯示的hello world位置向右偏移一個字元，導致d不見了

**Comment by kxgio** [comment]
可否截圖？

**Comment by b03611010** [comment]
速度太快不好截，但應該能看出來world應該為5個char，然而畫面只有4個




KANGXI <notifications@github.com>於 2017年8月13日 週日，上午2:35寫道：

**Comment by brownsugar** [comment]
是說這個吧
![image](https://user-images.githubusercontent.com/2935980/29253371-607b1a34-80ad-11e7-8057-f0575959408e.png)

**Comment by kxgio** [comment]
@b03611010 請問你的裝置和瀏覽器是？

**Comment by b03611010** [comment]
Hi,
iphone SE
safari瀏覽器哦

KANGXI <notifications@github.com>於 2017年8月14日 週一，上午11:04寫道：

**Comment by b03611010** [comment]
對，就是L大說的這個XD

Lay <notifications@github.com>於 2017年8月14日 週一，上午4:59寫道：
