### ISSUE TITLE
Code的註解在網頁上的預覽會被解析成url

### ISSUE THREAD

**Issue by maple3142** [kobeengineer/init#16]
如題
以下面code來說"//print"會被解析成"https://print"
```java
System.out.println("Hello World");
//print hello world
```

**Comment by kxgio** [comment]
請問這個問題是出現在「網站的文章頁面」裡，還是出現在文章發佈到臉書時？

**Comment by maple3142** [comment]
@kxgio 在網站的文章頁面

**Comment by HrJasn** [comment]
咦 被關掉了 話說這只能在精確度和方便程度上做取捨
要更精確的話差不多要這樣：
(http[s]?://.*\..*)|(.*\..*\..*)
要兼具精確與方便的話就要
.*\..*
然後再串namechk.com的API(想弄死版主就對了xDDD
