### ISSUE TITLE
為什麼被封鎖？

### ISSUE THREAD

**Issue by haer0248** [kobeengineer/init#18]
我明明沒有洗版，做出不違反純靠北工程師的事情但我卻被封鎖？
難道只是為了我下 * 叫所有工具人出來？

**Comment by haer0248** [comment]
還有 只是因為我私訊給純靠北工程師手機不能點列表這個Bug？

**Comment by kxgio** [comment]
你的封鎖狀況是臉書無法看到專頁還是在系統無法發文？

**Comment by haer0248** [comment]
那應該是年齡問題了 .. 謝謝

**Comment by haer0248** [comment]
突然可以看到了耶...
