### ISSUE TITLE
登入授權後出現unknown error

### ISSUE THREAD

**Issue by austin880625** [kobeengineer/init#2]
如附圖
![screen shot 2017-08-07 at 1 26 57 am](https://user-images.githubusercontent.com/8441337/29005529-a85c3b88-7b0f-11e7-96e8-c2811ed786ff.png)

**Comment by brownsugar** [comment]
+1

**Comment by dmhs110005** [comment]
同樣github無法登入

**Comment by win98se** [comment]
一样！

**Comment by UnKnoWn-Consortium** [comment]
Same here with Github login

**Comment by alpha8196** [comment]
同
{"error":{"message":"An unknown error has occurred."}}

**Comment by DF-wu** [comment]
與上方相同問題

**Comment by benbenbang** [comment]
+1 QQ

**Comment by kxgio** [comment]
短時間大量的人註冊，導致trigger到github api的存取限制，然後又忘記寫try cache所以噴了這個錯誤

目前已經取消驗證public repo
有遇到相同問題的人請至首頁按下面的re-auth按鈕重新驗證
