### ISSUE TITLE
帳號被判斷條件不符合

### ISSUE THREAD

**Issue by michael34435** [kobeengineer/init#3]
帳號建立時間 2013年，有超過10個以上的專案(不含透過organization建立的)

![2017-08-07 1 37 06](https://user-images.githubusercontent.com/3980983/29005619-7d72c50c-7b11-11e7-8a9e-86ebebdb6f68.png)
![2017-08-07 1 37 29](https://user-images.githubusercontent.com/3980983/29005620-82691b06-7b11-11e7-8373-a64bd6d864d9.png)

**Comment by kxgio** [comment]
這是跟 #2 相關的問題

在auth 跟 github拿資料時無法取得你的repos data (403 Forbidden)
所以暫時性的先讓你可以正常註冊帳號，但是狀態會顯示為未審核通過
預設的內容是寫給新註冊帳號看的，這點抱歉

目前還在思考怎麼處理

**Comment by ThisTNTSquid** [comment]
這個問題我也有，帳號很久之前已經開了，而且都用來放插件源碼，不過就通過不了

**Comment by kxgio** [comment]
目前已取消驗證public repo
請至 https://init.kobeengineer.io/ 點擊re-auth按鈕重新驗證

**Comment by michael34435** [comment]
有考慮排程處理嗎？一個帳號間隔30秒才能認證

**Comment by michael34435** [comment]
排程處理認證問題的話就可以規避掉頻繁存取github api的問題了，或是用爬蟲去看repo?

**Comment by michael34435** [comment]
ref: https://developer.github.com/changes/2013-07-02-rate-limit-reset/

在job裡面實作然後一個一個處理應該可行，如果有需要幫忙我可以出一個demo給你 😆

**Comment by kxgio** [comment]
暫時沒有考慮排程，因為這樣有的人可能需要等很久才會完成驗證

**Comment by michael34435** [comment]
準備多個github app然後用完了就換下一個的方法呢？
