### ISSUE TITLE
程式碼 Language & Theme 無法選擇

### ISSUE THREAD

**Issue by brownsugar** [kobeengineer/init#6]
兩個下拉選單皆無選項

![image](https://user-images.githubusercontent.com/2935980/29005897-0a07e708-7b18-11e7-969d-aec64975dad9.png)
![image](https://user-images.githubusercontent.com/2935980/29005891-c519654a-7b17-11e7-9ae6-5718cdb5c4c1.png)

**Comment by kxgio** [comment]
fixed.
